-- =====================================================
-- Savveyra
-- v0.1.56_Quotation_Supabase_Foundation_Complete
-- Quotation Supabase Foundation
-- =====================================================
--
-- Purpose:
--   Event-centered Quotation/Sales inbox foundation.
--   Supports Kitchen Updates, multiple Quotes per Event,
--   Draft -> Issued -> Accepted lifecycle, Supabase-owned
--   quote numbering, quote import/update, duplication,
--   issue, accept, and calculated financial views.
--
-- Notes:
--   - QuotationList is Event-centered.
--   - Quotes are commercial documents inside an Event workspace.
--   - Supabase owns business rules.
--   - Appsmith owns UX/buttons/modals/navigation.
--
-- =====================================================


-- =====================================================
-- Block 1
-- Tables / Columns / Constraints / Indexes
-- =====================================================

alter table public.evt_items
  add column if not exists quotation_revision_no integer not null default 1;


create table if not exists public.quo_event_inbox (
  id bigint generated by default as identity primary key,
  client_id uuid not null,
  event_id bigint not null references public.evt_items(id),

  hidden boolean not null default false,
  last_seen_event_revision_no integer,
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint quo_event_inbox_client_event_unique unique (client_id, event_id)
);


create table if not exists public.quo_events (
  id bigint generated by default as identity primary key,
  client_id uuid not null,
  event_id bigint not null references public.evt_items(id),

  quote_status text not null default 'Draft',
  quote_number text,
  quote_reference text,
  quote_date date default current_date,
  valid_until date,

  pricing_mode text not null default 'per_menu',
  event_price_total numeric,
  service_charge numeric,
  final_due_date date,

  imported_event_revision_no integer,
  last_update_all_at timestamptz,

  issued_at timestamptz,
  accepted_at timestamptz,

  customer_notes text,
  internal_notes text,
  terms text,

  active boolean not null default true,
  deleted boolean not null default false,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create table if not exists public.quo_menus (
  id bigint generated by default as identity primary key,
  quote_event_id bigint not null references public.quo_events(id) on delete cascade,
  client_id uuid not null,
  event_id bigint not null,
  event_component_id bigint,
  menu_id bigint,

  line_no integer not null,
  menu_name text,
  guests numeric,
  cost numeric,

  price_per_guest numeric,
  notes text,

  allergen_names text,
  diet_tag_names text,

  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create table if not exists public.quo_deposits (
  id bigint generated by default as identity primary key,
  quote_event_id bigint not null references public.quo_events(id) on delete cascade,
  client_id uuid not null,

  line_no integer not null,
  label text not null,
  amount numeric,
  due_date date,
  notes text,

  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);


create table if not exists public.document_sequences (
  id bigint generated by default as identity primary key,
  client_id uuid not null,
  document_type text not null,

  prefix text not null default 'SAV-',
  next_number integer not null default 1001,
  padding integer not null default 6,

  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint document_sequences_client_type_unique
    unique (client_id, document_type)
);


-- Existing-schema cleanup / normalization
alter table public.quo_events
  drop constraint if exists quo_events_event_unique;

alter table public.quo_events
  drop column if exists tax,
  drop column if exists subtotal,
  drop column if exists discount,
  drop column if exists total_quote,
  drop column if exists quote_ref;

alter table public.quo_events
  add column if not exists quote_number text,
  add column if not exists quote_reference text,
  add column if not exists pricing_mode text not null default 'per_menu',
  add column if not exists event_price_total numeric,
  add column if not exists service_charge numeric,
  add column if not exists final_due_date date,
  add column if not exists imported_event_revision_no integer,
  add column if not exists last_update_all_at timestamptz,
  add column if not exists issued_at timestamptz,
  add column if not exists accepted_at timestamptz;

alter table public.quo_menus
  add column if not exists price_per_guest numeric;


do $$
begin
  if exists (
    select 1
    from information_schema.columns
    where table_schema = 'public'
      and table_name = 'quo_menus'
      and column_name = 'sell_price'
  ) then
    execute '
      update public.quo_menus
      set price_per_guest = sell_price
      where price_per_guest is null
        and sell_price is not null
    ';

    alter table public.quo_menus
      drop column sell_price;
  end if;
end $$;


alter table public.quo_events
  drop constraint if exists quo_events_quote_status_chk;

update public.quo_events
set quote_status = 'Draft'
where quote_status not in ('Draft', 'Issued', 'Accepted')
   or quote_status is null;

alter table public.quo_events
  add constraint quo_events_quote_status_chk
  check (quote_status in ('Draft', 'Issued', 'Accepted'));


alter table public.quo_events
  drop constraint if exists quo_events_pricing_mode_chk;

alter table public.quo_events
  add constraint quo_events_pricing_mode_chk
  check (pricing_mode in ('per_menu', 'event_total'));


create unique index if not exists ux_quo_events_quote_number
  on public.quo_events(client_id, quote_number)
  where quote_number is not null;

create index if not exists idx_quo_event_inbox_client
  on public.quo_event_inbox(client_id);

create index if not exists idx_quo_event_inbox_event
  on public.quo_event_inbox(event_id);

create index if not exists idx_quo_events_client_event
  on public.quo_events(client_id, event_id);

create index if not exists idx_quo_events_status
  on public.quo_events(client_id, quote_status);

create index if not exists idx_quo_menus_quote_event
  on public.quo_menus(quote_event_id);

create unique index if not exists ux_quo_deposits_quote_line
  on public.quo_deposits(quote_event_id, line_no);


-- =====================================================
-- Block 2
-- Shared Document Numbering Service
-- =====================================================

drop function if exists public.get_next_document_number(uuid, text);

create or replace function public.get_next_document_number(
  p_client_id uuid,
  p_document_type text
)
returns text
language plpgsql
as $function$
declare
  v_prefix text;
  v_next_number integer;
  v_padding integer;
  v_document_number text;
begin
  select
    ds.prefix,
    ds.next_number,
    ds.padding
  into
    v_prefix,
    v_next_number,
    v_padding
  from public.document_sequences ds
  where ds.client_id = p_client_id
    and ds.document_type = p_document_type
    and ds.active = true
  for update;

  if v_next_number is null then
    raise exception 'Document numbering settings not found for %.%', p_client_id, p_document_type;
  end if;

  v_document_number :=
    coalesce(v_prefix, '') ||
    lpad(v_next_number::text, greatest(coalesce(v_padding, 0), 0), '0');

  update public.document_sequences ds
  set
    next_number = v_next_number + 1,
    updated_at = now()
  where ds.client_id = p_client_id
    and ds.document_type = p_document_type
    and ds.active = true;

  return v_document_number;
end;
$function$;


-- =====================================================
-- Block 3
-- Core Quotation Functions
-- =====================================================

drop function if exists public.sync_quotation_eligibility(uuid);
drop function if exists public.refresh_quotation_menus(bigint);
drop function if exists public.ensure_quotation_deposits(bigint);
drop function if exists public.import_event_to_quote(uuid, bigint, bigint);
drop function if exists public.update_quote_from_kitchen(bigint, text);
drop function if exists public.issue_quote(bigint, text);
drop function if exists public.issue_quote(bigint);
drop function if exists public.accept_quote(bigint);
drop function if exists public.duplicate_quote(bigint);


-- -----------------------------------------------------
-- sync_quotation_eligibility
--
-- Purpose:
--   Maintains Event-centered Sales inbox.
--   Adds eligible Events to QuotationList.
--
-- Called from:
--   QuotationList / sync action / later Event status workflows.
--
-- Notes:
--   Does not delete/deactivate quote documents.
-- -----------------------------------------------------
create or replace function public.sync_quotation_eligibility(
  p_client_id uuid
)
returns table(
  inserted_count integer,
  updated_count integer
)
language plpgsql
as $function$
declare
  v_inserted integer := 0;
  v_updated integer := 0;
begin
  insert into public.quo_event_inbox
  (
    client_id,
    event_id,
    hidden
  )
  select
    e.client_id,
    e.id,
    false
  from public.evt_items e
  where e.client_id = p_client_id
    and e.status in ('Sent', 'Ordered', 'Accepted')
    and coalesce(e.deleted, false) = false
  on conflict (client_id, event_id) do nothing;

  get diagnostics v_inserted = row_count;

  update public.quo_event_inbox qi
  set
    hidden = false,
    updated_at = now()
  where qi.client_id = p_client_id
    and qi.hidden = true
    and exists (
      select 1
      from public.evt_items e
      where e.id = qi.event_id
        and e.client_id = qi.client_id
        and e.status in ('Sent', 'Ordered', 'Accepted')
        and coalesce(e.deleted, false) = false
    );

  get diagnostics v_updated = row_count;

  return query select v_inserted, v_updated;
end;
$function$;


-- -----------------------------------------------------
-- refresh_quotation_menus
--
-- Purpose:
--   Refreshes Draft quote menu rows from current Event.
--
-- Called from:
--   import_event_to_quote()
--
-- Notes:
--   Preserves manual price_per_guest and notes when the same
--   event_component_id still exists.
-- -----------------------------------------------------
create or replace function public.refresh_quotation_menus(
  p_quote_event_id bigint
)
returns table(menu_rows integer)
language plpgsql
as $function$
declare
  v_client_id uuid;
  v_event_id bigint;
  v_rows integer := 0;
begin
  select
    client_id,
    event_id
  into
    v_client_id,
    v_event_id
  from public.quo_events
  where id = p_quote_event_id
    and quote_status = 'Draft'
    and coalesce(deleted, false) = false;

  if v_client_id is null then
    raise exception 'Draft quotation not found or quote is locked.';
  end if;

  create temporary table tmp_quo_menus_existing on commit drop as
  select *
  from public.quo_menus
  where quote_event_id = p_quote_event_id;

  delete from public.quo_menus
  where quote_event_id = p_quote_event_id;

  insert into public.quo_menus
  (
    quote_event_id,
    client_id,
    event_id,
    event_component_id,
    menu_id,
    line_no,
    menu_name,
    guests,
    cost,
    price_per_guest,
    notes,
    allergen_names,
    diet_tag_names,
    active
  )
  select
    p_quote_event_id,
    v_client_id,
    v_event_id,
    ec.id,
    ec.menu_id,
    ec.line_no,
    ec.menu_name,
    ec.guests,
    ec.line_cost,
    old.price_per_guest,
    old.notes,
    ec.allergen_names,
    ec.diet_tag_names,
    true
  from public.vw_evt_components ec
  left join tmp_quo_menus_existing old
    on old.event_component_id = ec.id
  where ec.event_id = v_event_id
    and ec.active = true
    and ec.menu_id is not null
  order by ec.line_no;

  get diagnostics v_rows = row_count;

  return query select v_rows;
end;
$function$;


-- -----------------------------------------------------
-- ensure_quotation_deposits
--
-- Purpose:
--   Ensures fixed visual deposit/payment rows exist.
--
-- Called from:
--   import_event_to_quote()
--
-- Notes:
--   Balance row is display support; actual balance is calculated in view.
-- -----------------------------------------------------
create or replace function public.ensure_quotation_deposits(
  p_quote_event_id bigint
)
returns table(deposit_rows integer)
language plpgsql
as $function$
declare
  v_client_id uuid;
  v_rows integer := 0;
begin
  select client_id
  into v_client_id
  from public.quo_events
  where id = p_quote_event_id
    and coalesce(deleted, false) = false;

  if v_client_id is null then
    raise exception 'Quotation event not found.';
  end if;

  insert into public.quo_deposits
  (
    quote_event_id,
    client_id,
    line_no,
    label
  )
  values
    (p_quote_event_id, v_client_id, 1, 'Deposit 1'),
    (p_quote_event_id, v_client_id, 2, 'Deposit 2'),
    (p_quote_event_id, v_client_id, 3, 'Deposit 3'),
    (p_quote_event_id, v_client_id, 4, 'Balance')
  on conflict (quote_event_id, line_no) do nothing;

  get diagnostics v_rows = row_count;

  return query select v_rows;
end;
$function$;


-- -----------------------------------------------------
-- import_event_to_quote
--
-- Purpose:
--   Imports current Event state into a Draft quote.
--
-- Called from:
--   update_quote_from_kitchen()
--   Appsmith direct action if needed.
--
-- Behavior:
--   - p_quote_event_id null = create new Draft.
--   - p_quote_event_id supplied = replace/update existing Draft.
-- -----------------------------------------------------
create or replace function public.import_event_to_quote(
  p_client_id uuid,
  p_event_id bigint,
  p_quote_event_id bigint default null
)
returns table(
  quote_event_id bigint,
  imported_event_revision_no integer,
  menu_rows integer,
  deposit_rows integer
)
language plpgsql
as $function$
declare
  v_quote_event_id bigint;
  v_event_revision_no integer;
  v_menu_rows integer := 0;
  v_deposit_rows integer := 0;
begin
  select quotation_revision_no
  into v_event_revision_no
  from public.evt_items
  where id = p_event_id
    and client_id = p_client_id
    and coalesce(deleted, false) = false;

  if v_event_revision_no is null then
    raise exception 'Event not found.';
  end if;

  if p_quote_event_id is not null then
    select id
    into v_quote_event_id
    from public.quo_events
    where id = p_quote_event_id
      and client_id = p_client_id
      and event_id = p_event_id
      and quote_status = 'Draft'
      and coalesce(deleted, false) = false;

    if v_quote_event_id is null then
      raise exception 'Draft quote not found or quote is locked.';
    end if;
  else
    insert into public.quo_events
    (
      client_id,
      event_id,
      quote_status,
      pricing_mode,
      imported_event_revision_no,
      quote_date,
      active,
      deleted
    )
    values
    (
      p_client_id,
      p_event_id,
      'Draft',
      'per_menu',
      v_event_revision_no,
      current_date,
      true,
      false
    )
    returning id into v_quote_event_id;
  end if;

  update public.quo_events
  set
    imported_event_revision_no = v_event_revision_no,
    last_update_all_at = now(),
    updated_at = now()
  where id = v_quote_event_id;

  select r.menu_rows
  into v_menu_rows
  from public.refresh_quotation_menus(v_quote_event_id) r;

  select d.deposit_rows
  into v_deposit_rows
  from public.ensure_quotation_deposits(v_quote_event_id) d;

  update public.quo_event_inbox
  set
    last_seen_event_revision_no = v_event_revision_no,
    updated_at = now()
  where client_id = p_client_id
    and event_id = p_event_id;

  return query select
    v_quote_event_id,
    v_event_revision_no,
    coalesce(v_menu_rows, 0),
    coalesce(v_deposit_rows, 0);
end;
$function$;


-- -----------------------------------------------------
-- update_quote_from_kitchen
--
-- Purpose:
--   Single Supabase entry point for Kitchen Update actions.
--
-- Called from:
--   Appsmith buttons:
--     - Import into Current Draft
--     - Import as New Draft
--
-- p_action:
--   replace_current
--   create_new
-- -----------------------------------------------------
create or replace function public.update_quote_from_kitchen(
  p_quote_event_id bigint,
  p_action text
)
returns table(
  quote_event_id bigint,
  event_id bigint,
  action_taken text,
  imported_event_revision_no integer,
  menu_rows integer,
  deposit_rows integer
)
language plpgsql
as $function$
declare
  v_client_id uuid;
  v_event_id bigint;
  v_new_quote_event_id bigint;
  v_event_revision_no integer;
  v_menu_rows integer := 0;
  v_deposit_rows integer := 0;
begin
  if p_action not in ('replace_current', 'create_new') then
    raise exception 'Invalid kitchen update action: %', p_action;
  end if;

  select
    q.client_id,
    q.event_id
  into
    v_client_id,
    v_event_id
  from public.quo_events q
  where q.id = p_quote_event_id
    and q.quote_status = 'Draft'
    and coalesce(q.deleted, false) = false;

  if v_client_id is null then
    raise exception 'Draft quote not found or quote is locked.';
  end if;

  select e.quotation_revision_no
  into v_event_revision_no
  from public.evt_items e
  where e.id = v_event_id
    and e.client_id = v_client_id
    and coalesce(e.deleted, false) = false;

  if v_event_revision_no is null then
    raise exception 'Event not found.';
  end if;

  if p_action = 'replace_current' then
    select
      i.quote_event_id,
      i.imported_event_revision_no,
      i.menu_rows,
      i.deposit_rows
    into
      v_new_quote_event_id,
      v_event_revision_no,
      v_menu_rows,
      v_deposit_rows
    from public.import_event_to_quote(
      v_client_id,
      v_event_id,
      p_quote_event_id
    ) i;

    return query select
      v_new_quote_event_id,
      v_event_id,
      'replace_current'::text,
      v_event_revision_no,
      v_menu_rows,
      v_deposit_rows;

    return;
  end if;

  if p_action = 'create_new' then
    select
      i.quote_event_id,
      i.imported_event_revision_no,
      i.menu_rows,
      i.deposit_rows
    into
      v_new_quote_event_id,
      v_event_revision_no,
      v_menu_rows,
      v_deposit_rows
    from public.import_event_to_quote(
      v_client_id,
      v_event_id,
      null
    ) i;

    return query select
      v_new_quote_event_id,
      v_event_id,
      'create_new'::text,
      v_event_revision_no,
      v_menu_rows,
      v_deposit_rows;

    return;
  end if;
end;
$function$;


-- -----------------------------------------------------
-- duplicate_quote
--
-- Purpose:
--   Creates a new Draft quote from any existing quote.
--
-- Notes:
--   Quote number / issued / accepted timestamps are not copied.
-- -----------------------------------------------------
create or replace function public.duplicate_quote(
  p_quote_event_id bigint
)
returns table(new_quote_event_id bigint)
language plpgsql
as $function$
declare
  v_new_id bigint;
begin
  insert into public.quo_events
  (
    client_id,
    event_id,
    quote_status,
    quote_reference,
    quote_date,
    valid_until,
    pricing_mode,
    event_price_total,
    service_charge,
    final_due_date,
    imported_event_revision_no,
    last_update_all_at,
    customer_notes,
    internal_notes,
    terms,
    active,
    deleted
  )
  select
    client_id,
    event_id,
    'Draft',
    quote_reference,
    current_date,
    valid_until,
    pricing_mode,
    event_price_total,
    service_charge,
    final_due_date,
    imported_event_revision_no,
    last_update_all_at,
    customer_notes,
    internal_notes,
    terms,
    true,
    false
  from public.quo_events
  where id = p_quote_event_id
    and coalesce(deleted, false) = false
  returning id into v_new_id;

  if v_new_id is null then
    raise exception 'Quote not found.';
  end if;

  insert into public.quo_menus
  (
    quote_event_id,
    client_id,
    event_id,
    event_component_id,
    menu_id,
    line_no,
    menu_name,
    guests,
    cost,
    price_per_guest,
    notes,
    allergen_names,
    diet_tag_names,
    active
  )
  select
    v_new_id,
    client_id,
    event_id,
    event_component_id,
    menu_id,
    line_no,
    menu_name,
    guests,
    cost,
    price_per_guest,
    notes,
    allergen_names,
    diet_tag_names,
    active
  from public.quo_menus
  where quote_event_id = p_quote_event_id
  order by line_no;

  insert into public.quo_deposits
  (
    quote_event_id,
    client_id,
    line_no,
    label,
    amount,
    due_date,
    notes
  )
  select
    v_new_id,
    client_id,
    line_no,
    label,
    amount,
    due_date,
    notes
  from public.quo_deposits
  where quote_event_id = p_quote_event_id
  order by line_no;

  return query select v_new_id;
end;
$function$;


-- -----------------------------------------------------
-- issue_quote
--
-- Purpose:
--   Locks a Draft quote and assigns official quote number.
--
-- Notes:
--   Supabase owns numbering.
--   Appsmith only calls Issue.
-- -----------------------------------------------------
create or replace function public.issue_quote(
  p_quote_event_id bigint
)
returns table(
  quote_event_id bigint,
  quote_number text,
  quote_status text
)
language plpgsql
as $function$
declare
  v_client_id uuid;
  v_quote_number text;
begin
  select q.client_id
  into v_client_id
  from public.quo_events q
  where q.id = p_quote_event_id
    and q.quote_status = 'Draft'
    and coalesce(q.deleted, false) = false;

  if v_client_id is null then
    raise exception 'Draft quote not found or quote is already locked.';
  end if;

  if not exists (
    select 1
    from public.quo_menus qm
    where qm.quote_event_id = p_quote_event_id
      and qm.active = true
  ) then
    raise exception 'Cannot issue a quote without menu rows.';
  end if;

  v_quote_number := public.get_next_document_number(v_client_id, 'quote');

  update public.quo_events q
  set
    quote_status = 'Issued',
    quote_number = v_quote_number,
    issued_at = coalesce(q.issued_at, now()),
    updated_at = now()
  where q.id = p_quote_event_id;

  return query
  select
    q.id,
    q.quote_number,
    q.quote_status
  from public.quo_events q
  where q.id = p_quote_event_id;
end;
$function$;


-- -----------------------------------------------------
-- accept_quote
--
-- Purpose:
--   Accepts an Issued quote.
--
-- Behavior:
--   - Quote must already be Issued.
--   - New Accepted quote becomes Accepted.
--   - Prior Accepted quote for same Event returns to Issued.
--   - Event status becomes Accepted.
-- -----------------------------------------------------
create or replace function public.accept_quote(
  p_quote_event_id bigint
)
returns table(
  quote_event_id bigint,
  event_id bigint,
  quote_number text,
  quote_status text
)
language plpgsql
as $function$
declare
  v_client_id uuid;
  v_event_id bigint;
begin
  select
    q.client_id,
    q.event_id
  into
    v_client_id,
    v_event_id
  from public.quo_events q
  where q.id = p_quote_event_id
    and q.quote_status = 'Issued'
    and coalesce(q.deleted, false) = false;

  if v_client_id is null then
    raise exception 'Only an issued quote can be accepted.';
  end if;

  update public.quo_events q
  set
    quote_status = 'Issued',
    updated_at = now()
  where q.client_id = v_client_id
    and q.event_id = v_event_id
    and q.id <> p_quote_event_id
    and q.quote_status = 'Accepted'
    and coalesce(q.deleted, false) = false;

  update public.quo_events q
  set
    quote_status = 'Accepted',
    accepted_at = now(),
    updated_at = now()
  where q.id = p_quote_event_id;

  update public.evt_items e
  set
    status = 'Accepted',
    status_changed_at = now(),
    updated_at = now()
  where e.id = v_event_id
    and e.client_id = v_client_id
    and coalesce(e.deleted, false) = false;

  return query
  select
    q.id,
    q.event_id,
    q.quote_number,
    q.quote_status
  from public.quo_events q
  where q.id = p_quote_event_id;
end;
$function$;


-- =====================================================
-- Block 4
-- Views
-- =====================================================

drop view if exists public.vw_quo_event_inbox;
drop view if exists public.vw_quo_menu_components;
drop view if exists public.vw_quo_menus;
drop view if exists public.vw_quo_events;


-- -----------------------------------------------------
-- vw_quo_events
-- Quote header / financial summary
-- -----------------------------------------------------
create or replace view public.vw_quo_events as
select
  qe.id as quote_event_id,
  qe.client_id,
  qe.event_id,

  e.name as event_name,
  e.event_ref,
  e.event_date,
  e.event_time,
  e.event_datetime,
  e.status as event_status,
  e.format,
  e.total_guests_manual,
  e.total_guests,
  e.total_cost as event_cost,

  e.customer_id,
  e.customer_name,
  e.company,
  e.contact_id,
  e.contact_person,
  e.phone,
  e.email,

  e.venue_id,
  e.venue_name,

  qe.quote_status,
  qe.quote_number,
  qe.quote_reference,
  qe.quote_date,
  qe.valid_until,
  qe.pricing_mode,
  qe.event_price_total,
  qe.service_charge,
  qe.final_due_date,
  qe.issued_at,
  qe.accepted_at,
  qe.imported_event_revision_no,
  qe.last_update_all_at,

  qe.customer_notes,
  qe.internal_notes,
  qe.terms,

  case
    when qe.pricing_mode = 'event_total'
      then coalesce(qe.event_price_total, 0)
    else coalesce((
      select sum(coalesce(qm.guests, 0) * coalesce(qm.price_per_guest, 0))
      from public.quo_menus qm
      where qm.quote_event_id = qe.id
        and qm.active = true
    ), 0)
  end as subtotal,

  coalesce(qe.service_charge, 0) as service_charge_amount,

  case
    when qe.pricing_mode = 'event_total'
      then coalesce(qe.event_price_total, 0)
    else coalesce((
      select sum(coalesce(qm.guests, 0) * coalesce(qm.price_per_guest, 0))
      from public.quo_menus qm
      where qm.quote_event_id = qe.id
        and qm.active = true
    ), 0)
  end + coalesce(qe.service_charge, 0) as quote_total,

  (
    case
      when qe.pricing_mode = 'event_total'
        then coalesce(qe.event_price_total, 0)
      else coalesce((
        select sum(coalesce(qm.guests, 0) * coalesce(qm.price_per_guest, 0))
        from public.quo_menus qm
        where qm.quote_event_id = qe.id
          and qm.active = true
      ), 0)
    end + coalesce(qe.service_charge, 0)
  )
  - coalesce((
      select sum(coalesce(qd.amount, 0))
      from public.quo_deposits qd
      where qd.quote_event_id = qe.id
    ), 0) as balance,

  qe.active,
  qe.deleted,
  qe.created_at,
  qe.updated_at
from public.quo_events qe
join public.vw_evt_items e
  on e.id = qe.event_id
 and e.client_id = qe.client_id
where coalesce(qe.deleted, false) = false;


-- -----------------------------------------------------
-- vw_quo_menus
-- Quote menu rows
-- -----------------------------------------------------
create or replace view public.vw_quo_menus as
select
  qm.id as quote_menu_id,
  qm.quote_event_id,
  qm.client_id,
  qm.event_id,
  qm.event_component_id,
  qm.menu_id,
  qm.line_no,

  qm.menu_name,
  qm.guests,
  qm.cost,
  qm.price_per_guest,
  coalesce(qm.guests, 0) * coalesce(qm.price_per_guest, 0) as line_total,
  qm.notes,
  qm.allergen_names,
  qm.diet_tag_names,
  qm.active,

  ec.extra_guests,
  ec.line_cost as current_line_cost,
  ec.menu_name as current_menu_name,
  ec.allergen_names as current_allergen_names,
  ec.diet_tag_names as current_diet_tag_names,
  ec.child_active,
  ec.child_deleted,
  ec.component_status,

  qm.created_at,
  qm.updated_at
from public.quo_menus qm
left join public.vw_evt_components ec
  on ec.id = qm.event_component_id
 and ec.event_id = qm.event_id;


-- -----------------------------------------------------
-- vw_quo_menu_components
-- Quote menu component display
-- -----------------------------------------------------
create or replace view public.vw_quo_menu_components as
select
  qm.id as quote_menu_id,
  qm.quote_event_id,
  qm.client_id,
  qm.event_id,
  qm.menu_id,

  mc.id as menu_component_id,
  mc.line_no,
  mc.item_type,
  mc.component_name,
  mc.component_category,
  mc.qty,
  mc.unit_abbreviation,
  mc.active,
  mc.child_active,
  mc.child_deleted,
  mc.component_status
from public.quo_menus qm
join public.vw_mnu_components mc
  on mc.menu_id = qm.menu_id
where qm.active = true;


-- -----------------------------------------------------
-- vw_quo_event_inbox
-- Event-centered Sales Inbox / QuotationList
-- -----------------------------------------------------
create or replace view public.vw_quo_event_inbox as
select
  qi.id as inbox_id,
  qi.client_id,
  qi.event_id,

  e.name as event_name,
  e.event_ref,
  e.event_date,
  e.event_datetime,
  e.status as event_status,
  e.format,
  e.total_guests,
  e.total_cost,
  e.customer_id,
  e.customer_name,
  e.company,
  e.contact_id,
  e.contact_person,
  e.venue_id,
  e.venue_name,

  ei.quotation_revision_no,

  qi.last_seen_event_revision_no,
  qi.hidden,

  case
    when exists (
      select 1
      from public.quo_events q
      where q.client_id = qi.client_id
        and q.event_id = qi.event_id
        and coalesce(q.deleted, false) = false
        and q.quote_status = 'Draft'
        and coalesce(q.imported_event_revision_no, 0) < coalesce(ei.quotation_revision_no, 1)
    )
    then true
    when not exists (
      select 1
      from public.quo_events q
      where q.client_id = qi.client_id
        and q.event_id = qi.event_id
        and coalesce(q.deleted, false) = false
    )
    then true
    else false
  end as kitchen_update_available,

  (
    select count(*)
    from public.quo_events q
    where q.client_id = qi.client_id
      and q.event_id = qi.event_id
      and coalesce(q.deleted, false) = false
      and q.quote_status = 'Draft'
  ) as draft_quote_count,

  (
    select count(*)
    from public.quo_events q
    where q.client_id = qi.client_id
      and q.event_id = qi.event_id
      and coalesce(q.deleted, false) = false
      and q.quote_status = 'Issued'
  ) as issued_quote_count,

  (
    select count(*)
    from public.quo_events q
    where q.client_id = qi.client_id
      and q.event_id = qi.event_id
      and coalesce(q.deleted, false) = false
      and q.quote_status = 'Accepted'
  ) as accepted_quote_count,

  (
    select q.quote_number
    from public.quo_events q
    where q.client_id = qi.client_id
      and q.event_id = qi.event_id
      and coalesce(q.deleted, false) = false
      and q.quote_status = 'Accepted'
    order by q.accepted_at desc nulls last, q.id desc
    limit 1
  ) as accepted_quote_number,

  qi.created_at,
  qi.updated_at
from public.quo_event_inbox qi
join public.evt_items ei
  on ei.id = qi.event_id
 and ei.client_id = qi.client_id
join public.vw_evt_items e
  on e.id = qi.event_id
 and e.client_id = qi.client_id
where qi.hidden = false
  and coalesce(ei.deleted, false) = false;


-- =====================================================
-- Optional Test Queries
-- =====================================================
--
-- select * from public.sync_quotation_eligibility('<client_id>'::uuid);
--
-- select * from public.vw_quo_event_inbox
-- where client_id = '<client_id>'::uuid;
--
-- select * from public.import_event_to_quote('<client_id>'::uuid, <event_id>, null);
--
-- select * from public.duplicate_quote(<quote_event_id>);
--
-- select * from public.issue_quote(<quote_event_id>);
--
-- select * from public.accept_quote(<quote_event_id>);
--
-- =====================================================
